import { normalizeRouterConfig } from "../src/config";
import type { RouterConfig } from "../src/types";

export function testConfig(): RouterConfig {
  return normalizeRouterConfig({
    policy: {
      allowTraining: false,
      allowLogging: false,
      allowChineseProviders: false,
      blockedRegions: ["cn"],
      byokOnly: true,
    },
    providers: [
      {
        id: "openai",
        displayName: "OpenAI",
        kind: "openai-compatible",
        baseUrl: "https://api.openai.test/v1",
        apiKeyEnv: "OPENAI_API_KEY",
        enabled: true,
        regions: ["us"],
        dataPolicy: {
          allowTraining: false,
          allowLogging: false,
          byokOnly: true,
          zeroDataRetentionAvailable: false,
        },
      },
      {
        id: "deepseek",
        displayName: "DeepSeek",
        kind: "openai-compatible",
        baseUrl: "https://api.deepseek.test",
        apiKeyEnv: "DEEPSEEK_API_KEY",
        enabled: true,
        regions: ["cn"],
        jurisdiction: "cn",
        dataPolicy: {
          allowTraining: false,
          allowLogging: true,
          byokOnly: true,
          zeroDataRetentionAvailable: false,
        },
      },
      {
        id: "openrouter",
        displayName: "OpenRouter",
        kind: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        apiKeyEnv: "OPENROUTER_API_KEY",
        enabled: true,
        regions: ["global"],
        dataPolicy: {
          allowTraining: false,
          allowLogging: true,
          byokOnly: true,
          zeroDataRetentionAvailable: false,
        },
        gateway: {
          kind: "openrouter",
          openAiCompatible: true,
          requestOptionsShape: "openrouter-provider",
        },
      },
      {
        id: "vercel-ai-gateway",
        displayName: "Vercel AI Gateway",
        kind: "openai-compatible",
        baseUrl: "https://ai-gateway.vercel.sh/v1",
        apiKeyEnv: "AI_GATEWAY_API_KEY",
        enabled: true,
        regions: ["global"],
        dataPolicy: {
          allowTraining: false,
          allowLogging: true,
          byokOnly: true,
          zeroDataRetentionAvailable: false,
        },
        gateway: {
          kind: "vercel-ai-gateway",
          openAiCompatible: true,
          requestOptionsShape: "vercel-provider-options",
        },
      },
    ],
    models: [
      {
        id: "openai/cheap",
        providerId: "openai",
        providerModel: "cheap",
        aliases: ["auto", "cheap"],
        capabilities: ["chat", "streaming", "json"],
        contextWindow: 128000,
        inputUsdPerMillionTokens: 0.1,
        outputUsdPerMillionTokens: 0.2,
        qualityScore: 0.55,
        averageLatencyMs: 500,
        successRate: 0.99,
        taskQuality: {
          "bulk-cheap": 0.9,
          "low-latency-chat": 0.86,
        },
      },
      {
        id: "openai/coding",
        providerId: "openai",
        providerModel: "coding",
        aliases: ["auto", "coding"],
        capabilities: ["chat", "streaming", "tools", "json", "reasoning"],
        contextWindow: 1000000,
        inputUsdPerMillionTokens: 1,
        outputUsdPerMillionTokens: 4,
        qualityScore: 0.85,
        averageLatencyMs: 1500,
        successRate: 0.99,
        taskQuality: {
          coding: 0.9,
          reasoning: 0.86,
          json: 0.85,
        },
        tags: ["coding"],
      },
      {
        id: "deepseek/coder",
        providerId: "deepseek",
        providerModel: "coder",
        aliases: ["auto", "coding", "china-coding"],
        capabilities: ["chat", "streaming", "tools"],
        contextWindow: 128000,
        inputUsdPerMillionTokens: 0.2,
        outputUsdPerMillionTokens: 0.8,
        qualityScore: 0.78,
        averageLatencyMs: 1200,
        successRate: 0.98,
        taskQuality: {
          coding: 0.88,
        },
        tags: ["coding"],
      },
      {
        id: "openrouter/auto",
        providerId: "openrouter",
        providerModel: "openrouter/auto",
        aliases: ["gateway-auto"],
        capabilities: ["chat", "streaming", "tools", "json", "reasoning", "vision"],
        contextWindow: 200000,
        qualityScore: 0.8,
      },
      {
        id: "vercel/coding",
        providerId: "vercel-ai-gateway",
        providerModel: "openai/gpt-4.1-mini",
        aliases: ["vercel-coding"],
        capabilities: ["chat", "streaming", "tools", "json"],
        contextWindow: 1000000,
        qualityScore: 0.82,
      },
    ],
    routes: [
      {
        id: "auto",
        mode: "smart",
        modelAliases: ["auto"],
        fallbackModelIds: ["openai/cheap", "openai/coding", "deepseek/coder"],
        dataPolicy: {
          allowTraining: false,
          allowLogging: false,
          allowChineseProviders: false,
          blockedRegions: ["cn"],
        },
      },
      {
        id: "coding",
        mode: "fallback",
        modelAliases: ["coding"],
        fallbackModelIds: ["deepseek/coder", "openai/coding"],
        dataPolicy: {
          allowTraining: false,
          allowLogging: false,
          allowChineseProviders: false,
          blockedRegions: ["cn"],
        },
      },
      {
        id: "china-coding",
        mode: "fallback",
        modelAliases: ["china-coding"],
        fallbackModelIds: ["deepseek/coder", "openai/coding"],
        dataPolicy: {
          allowTraining: false,
          allowLogging: true,
          allowChineseProviders: true,
          allowedRegions: ["cn", "us"],
        },
      },
      {
        id: "gateway-auto",
        mode: "smart",
        modelAliases: ["gateway-auto"],
        fallbackModelIds: ["openrouter/auto", "vercel/coding"],
        dataPolicy: {
          allowTraining: false,
          allowLogging: true,
          allowChineseProviders: false,
        },
      },
    ],
  });
}
